default: &default
  adapter: postgresql
  encoding: unicode
  database: 
  username: membership_db_user
  password: membership_db_password
  host: localhost
  port: 9999

development:
  <<: *default
  database: membership_dvelopment

test:
  <<: *default
  database: membership_test

production:
  <<: *default
  database: membership_production
  
  