default: &default
  adapter: postgresql
  encoding: unicode
  username:
  password:
  host: localhost

development:
  <<: *default
  database: membership_dvelopment
  username: membership_db_user
  password: membership_db_password
  port: 9999

test:
  <<: *default
  database: membership_test

production:
  <<: *default
  database: membership_production
  
  